# Generated by Django 4.1.1 on 2022-10-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_translatetexts_language_code_destiny'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_to_upload', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='translatetexts',
            name='language_code_destiny',
            field=models.CharField(choices=[('en', 'english'), ('fr', 'france'), ('de', 'deutch')], max_length=2),
        ),
    ]
