# Generated by Django 4.0.6 on 2022-10-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_remove_sentimenttexts_sentiment_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_to_upload', models.FileField(upload_to='')),
            ],
        ),
    ]
