# Generated by Django 4.0.6 on 2022-10-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_uploadfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfolder',
            name='File_to_upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
