# Generated by Django 4.0.6 on 2022-10-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_alter_uploadfolder_file_to_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfolder',
            old_name='File_to_upload',
            new_name='file_to_upload',
        ),
    ]
